Feature/Routing
Betra/Duchamp pull request #10
Opened 2019-03-03 21:42 UTC by Betra

2019-03-05 17:18 UTC, fletcherist requested changes

2019-03-05 17:18 UTC, fletcherist commented on src/utils/buildLayout.js
> +  var col_heights = []
use camel case for var names pls

2019-03-05 17:18 UTC, fletcherist commented on src/Сomponents/Footer/Footer.js
> +       rel='noopener noreferrer'>
not bad!!!!!!!!!
obama.jpg

2019-03-05 17:18 UTC, fletcherist commented on src/Сomponents/Form/Form.js
> +      <section className="formInput">
dont know, but it seems that 
`import './Form.module.css';`

imports css into global namespace. here you loose all the advantages of css modules

heres a better way to do it
`import css from './Fork.module.css'`
`<section className={css.formInput}>`


but actually i dont know. need some researching

2019-03-06 23:46 UTC, Betra commented on src/Сomponents/Form/Form.js
> +      <section className="formInput">
Global fix: 3e5f5a7
Почему-то юзал import **{** styles **}**, из-за это часто возникали TypeError, сейчас понял

2019-03-06 23:50 UTC, Betra commented on src/utils/buildLayout.js
> +  var col_heights = []
Done
ca1ac1d

2019-03-08 08:34 UTC, merged