Feature/Redux + Refacturing
Betra/Duchamp pull request #15
Opened 2019-03-15 15:34 UTC by Betra

2019-03-16 13:19 UTC, fletcherist requested changes

2019-03-16 13:19 UTC, fletcherist commented on src/store.js
> +const article = (state, action) => {
а зачем нужен этот «редьюсер». какой смысл он даёт. почему не объединил его вместе с `articlesReducer`?

2019-03-16 13:19 UTC, fletcherist commented on src/Сomponents/Form/Form.js
> +export const Form = React.forwardRef(
найс, топ использование

2019-03-18 19:40 UTC, Betra commented on src/Сomponents/Form/Form.js
> +export const Form = React.forwardRef(
Sorry, no more ref ;c 
52ad74b

2019-03-18 19:42 UTC, Betra commented on src/store.js
> +const article = (state, action) => {
Fixed 

2934fbf

f0ef3a4

2019-03-19 10:11 UTC, merged